In [1]:
import numpy as np
import pandas as pd

In [2]:
UN = 'UN_MigrantStockTotal_2015.xlsx'
#  read all the tables into pandas dataframes, 
#  row 14 & 15 as row names, for simplicity we use row 15 as header
#  and read the rest rows as data
dfs = pd.read_excel(UN, sheet_name=None, header=[15])

In [3]:
# sheets are sorted as a dictionary, where
#   keys are sheet names
#   values are data frames
dfs.keys()

dict_keys(['CONTENTS', 'Table 1', 'Table 2', 'Table 3', 'Table 4', 'Table 5', 'Table 6', 'ANNEX', 'NOTES'])

# Table 1: International Migrant Stock at Mid-Year 

In [4]:
table1 = dfs['Table 1']
table1.head() 

Unnamed: 0                                         Unnamed: 1 Unnamed: 2  \
0           1                                              WORLD        NaN   
1           2                                  Developed regions        (b)   
2           3                                 Developing regions        (c)   
3           4                          Least developed countries        (d)   
4           5  Less developed regions excluding least develop...        NaN   

   Unnamed: 3 Unnamed: 4       1990       1995       2000       2005  \
0         900        NaN  152563212  160801752  172703309  191269100   
1         901        NaN   82378628   92306854  103375363  117181109   
2         902        NaN   70184584   68494898   69327946   74087991   
3         941        NaN   11075966   11711703   10077824    9809634   
4         934        NaN   59105261   56778501   59244124   64272611   

        2010  ...    2000.1    2005.1     2010.1     2015.1    1990.2  \
0  221714243  ...  87884839  97866674  114613714  126115435  74815702   
1  132560325  ...  50536796  57217777   64081077   67618619  42115231   
2   89153918  ...  37348043  40648897   50532637   58496816  32700471   
3   10018128  ...   5361902   5383009    5462714    6463217   5236216   
4   79130668  ...  31986141  35265888   45069923   52033599  27464255   

     1995.2    2000.2    2005.2     2010.2     2015.2  
0  79064275  84818470  93402426  107100529  117584801  
1  47214055  52838567  59963332   68479248   72863336  
2  31850220  31979903  33439094   38621281   44721465  
3   5573685   4721920   4432371    4560536    5493028  
4  26276535  27257983  29006723   34060745   39228437  

[5 rows x 23 columns]

There are some columns without proper names, which need to be renamed for clarity.

In [5]:
table1 = table1.rename(columns = {'Unnamed: 0':"Order",
                                  'Unnamed: 1':"Destination",
                                  'Unnamed: 2':'Notes',
                                  'Unnamed: 3':'Country Code',
                                  'Unnamed: 4':'Data Type'})
# Drop some columns which are not useful for our table.
# Clean the table by replacing '..' values with NaN
table1 = (table1.
          drop(columns=['Notes','Data Type'],axis = 1).
          replace('..', np.nan))
table1.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

          1990         1995         2000         2005       2010       2015  \
0  152563212.0  160801752.0  172703309.0  191269100.0  221714243  243700236   
1   82378628.0   92306854.0  103375363.0  117181109.0  132560325  140481955   
2   70184584.0   68494898.0   69327946.0   74087991.0   89153918  103218281   
3   11075966.0   11711703.0   10077824.0    9809634.0   10018128   11951316   
4   59105261.0   56778501.0   59244124.0   64272611.0   79130668   91262036   

       1990.1  ...      2000.1      2005.1     2010.1     2015.1      1990.2  \
0  77747510.0  ...  87884839.0  97866674.0  114613714  126115435  74815702.0   
1  40263397.0  ...  50536796.0  57217777.0   64081077   67618619  42115231.0   
2  37484113.0  ...  37348043.0  40648897.0   50532637   58496816  32700471.0   
3   5843107.0  ...   5361902.0   5383009.0    5462714    6463217   5236216.0   
4  31641006.0  ...  31986141.0  35265888.0   45069923   52033599  27464255.0   

       1995.2      2000.2      2005.2     2010.2     2015.2  
0  79064275.0  84818470.0  93402426.0  107100529  117584801  
1  47214055.0  52838567.0  59963332.0   68479248   72863336  
2  31850220.0  31979903.0  33439094.0   38621281   44721465  
3   5573685.0   4721920.0   4432371.0    4560536    5493028  
4  26276535.0  27257983.0  29006723.0   34060745   39228437  

[5 rows x 21 columns]

We can find that the column names are year values but not variable names, that the variable is spread across columns.

**Thus, by tidy data principle 1, column headers should be names, no values. Thus we need to turn columns into rows.**

In [6]:
# Rename the columns for both sexes by adding .0 at the end of the year
table1 = table1.rename(columns = {1990:"1990.0",
                                  1995:"1995.0",
                                  2000:'2000.0',
                                  2005:'2005.0',
                                  2010:'2010.0',
                                  2015:'2015.0'})

# Using melt function to turn columns into one single varible 'Year', 
#   storing their values into a new column 'International migrant stock'
table1 = table1.melt(id_vars=["Order","Destination","Country Code"], 
                     var_name = "Year", value_name = "International Migrant Stock")
table1.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

     Year  International Migrant Stock  
0  1990.0                  152563212.0  
1  1990.0                   82378628.0  
2  1990.0                   70184584.0  
3  1990.0                   11075966.0  
4  1990.0                   59105261.0

However, the Year column contains not only years but also gender that there are multiple variables stored in 1 column. 

**By tidy data principle 2: each column needs to consist of one and only one variable, thus we split 'Year' column into 'Year' and 'Gender'.**

In [7]:
# Create a new column Gender by obtaining the last digit of Year 
table1 = table1.assign(Gender = lambda x: x.Year.str[-1])
table1['Gender'] = table1['Gender'].apply(lambda x: "Male" if (x == "1") 
                                          else ("Both Sexes" if (x == "0") else "Female"))

# Modify Year by dropping the last digit
table1 =(table1.assign(Year = lambda x: x.Year.str[:-2].astype(str)))
table1.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

   Year  International Migrant Stock      Gender  
0  1990                  152563212.0  Both Sexes  
1  1990                   82378628.0  Both Sexes  
2  1990                   70184584.0  Both Sexes  
3  1990                   11075966.0  Both Sexes  
4  1990                   59105261.0  Both Sexes

# tidy_table()

We can find the structures of tables are quite similar, which means we can define a function tidy_table to organize the steps of data cleaning and enable repeated use.

Tidy Steps:

    1. clean the table by replacing missing values to NaN 
    2. by princple 1, year-related columns to a single varible Year
    3. by princple 2, split 'Year' column into 'Year' and 'Gender' 

In [8]:
# function takes two variables: table t, and a name for the main values stored in this table
#    returns the tidy table, splitted major_area table, splitted countries table
def tidy_table(t, name): 
    t = (t.melt(id_vars=["Order","Destination","Country Code"],  # principle 1
                var_name = "Year", value_name = name).
         assign(Gender = lambda x: x.Year.str[-1]))            # principle 2
    
    # replace gender values to descriptive values
    t['Gender'] = t['Gender'].apply(lambda x: "Male" if (x == "1") 
                                          else ("Both Sexes" if (x == "0") else "Female"))
    t = (t.assign(Year = lambda x: x.Year.str[:-2].astype(str)))
    return t

# Table 2: Total Population by Sex at Mid-Year 

In [9]:
table2 = dfs['Table 2']
table2.head() 

Unnamed: 0                                         Unnamed: 1 Unnamed: 2  \
0           1                                              WORLD        NaN   
1           2                                  Developed regions        (b)   
2           3                                 Developing regions        (c)   
3           4                          Least developed countries        (d)   
4           5  Less developed regions excluding least develop...        NaN   

   Unnamed: 3         1990         1995         2000         2005  \
0         900  5309667.699  5735123.084  6126622.121  6519635.850   
1         901  1144463.062  1169761.211  1188811.731  1208919.509   
2         902  4165204.637  4565361.873  4937810.390  5310716.341   
3         941   510057.629   585189.354   664386.087   752804.951   
4         934  3655147.008  3980172.519  4273424.303  4557911.390   

          2010         2015  ...       2000.1       2005.1       2010.1  \
0  6929725.043  7349472.099  ...  3084537.662  3285082.249  3493956.904   
1  1233375.711  1251351.086  ...   578010.218   587962.213   599955.476   
2  5696349.332  6098121.013  ...  2506527.444  2697120.036  2894001.428   
3   847254.847   954157.804  ...   331482.475   375757.715   422397.532   
4  4849094.485  5143963.209  ...  2175044.969  2321362.321  2471603.896   

        2015.1       1990.2       1995.2       2000.2       2005.2  \
0  3707205.753  2639243.998  2848487.191  3042084.459  3234553.601   
1   609297.148   589207.436   601492.755   610801.513   620957.296   
2  3097908.605  2050036.562  2246994.436  2431282.946  2613596.305   
3   476031.179   256015.073   293162.612   332903.612   377047.236   
4  2621877.426  1794021.489  1953831.824  2098379.334  2236549.069   

        2010.2       2015.2  
0  3435768.139  3642266.346  
1   633420.235   642053.938  
2  2802347.904  3000212.408  
3   424857.315   478126.625  
4  2377490.589  2522085.783  

[5 rows x 22 columns]

Same as what we did for table 1, here we need to prepare for cleaning by giving proper variable names for the table and dropping not useful columns 

In [10]:
# Rename columns, drop not useful columns
# replace '..' values with 0, which will be replaced back to NaN at the end
table2 = (table2.
          rename(columns = {'Unnamed: 0':"Order",
                            'Unnamed: 1':"Destination",
                            'Unnamed: 2':'Notes',
                            'Unnamed: 3':'Country Code',
                            1990:"1990.0", 1995:"1995.0", 2000:'2000.0',
                            2005:'2005.0', 2010:'2010.0', 2015:'2015.0'}).
          drop(columns=['Notes'],axis = 1).
         replace("..", np.nan))
table2.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

        1990.0       1995.0       2000.0       2005.0       2010.0  \
0  5309667.699  5735123.084  6126622.121  6519635.850  6929725.043   
1  1144463.062  1169761.211  1188811.731  1208919.509  1233375.711   
2  4165204.637  4565361.873  4937810.390  5310716.341  5696349.332   
3   510057.629   585189.354   664386.087   752804.951   847254.847   
4  3655147.008  3980172.519  4273424.303  4557911.390  4849094.485   

        2015.0       1990.1  ...       2000.1       2005.1       2010.1  \
0  7349472.099  2670423.701  ...  3084537.662  3285082.249  3493956.904   
1  1251351.086   555255.626  ...   578010.218   587962.213   599955.476   
2  6098121.013  2115168.075  ...  2506527.444  2697120.036  2894001.428   
3   954157.804   254042.556  ...   331482.475   375757.715   422397.532   
4  5143963.209  1861125.519  ...  2175044.969  2321362.321  2471603.896   

        2015.1       1990.2       1995.2       2000.2       2005.2  \
0  3707205.753  2639243.998  2848487.191  3042084.459  3234553.601   
1   609297.148   589207.436   601492.755   610801.513   620957.296   
2  3097908.605  2050036.562  2246994.436  2431282.946  2613596.305   
3   476031.179   256015.073   293162.612   332903.612   377047.236   
4  2621877.426  1794021.489  1953831.824  2098379.334  2236549.069   

        2010.2       2015.2  
0  3435768.139  3642266.346  
1   633420.235   642053.938  
2  2802347.904  3000212.408  
3   424857.315   478126.625  
4  2377490.589  2522085.783  

[5 rows x 21 columns]

In [11]:
table2 = tidy_table(table2,"Total Population (thousands)")  
table2

Order                                        Destination  Country Code  \
0         1                                              WORLD           900   
1         2                                  Developed regions           901   
2         3                                 Developing regions           902   
3         4                          Least developed countries           941   
4         5  Less developed regions excluding least develop...           934   
...     ...                                                ...           ...   
4765    261                                              Samoa           882   
4766    262                                            Tokelau           772   
4767    263                                              Tonga           776   
4768    264                                             Tuvalu           798   
4769    265                          Wallis and Futuna Islands           876   

      Year  Total Population (thousands)      Gender  
0     1990                   5309667.699  Both Sexes  
1     1990                   1144463.062  Both Sexes  
2     1990                   4165204.637  Both Sexes  
3     1990                    510057.629  Both Sexes  
4     1990                   3655147.008  Both Sexes  
...    ...                           ...         ...  
4765  2015                        93.584      Female  
4766  2015                           NaN      Female  
4767  2015                        52.931      Female  
4768  2015                           NaN      Female  
4769  2015                           NaN      Female  

[4770 rows x 6 columns]

# Table 3: International Migrant Stock as a Percentage of the Total Population

Table 3 stores the International migrant stock as a percentage of the total population. 

Recall that table 1 stores International migrant stock at mid-year; table 2 stores Total population at mid-year (thousands).

**We can find that values in table 3 can be derived by table1/table2**.

And values in three tables are all organized by the same index sets: 'Order','destination','Country Code', which means there are many redundant valeus stored in those three tables. 

**By principle 5, a single observational units must be in 1 table, thus we need to combine these three tables.**

In [12]:
# Combine Table 1 and Table 2  
joined_table = table1.copy()
joined_table = joined_table.merge(table2, on=["Order","Destination","Country Code","Year","Gender"])
joined_table.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

   Year  International Migrant Stock      Gender  Total Population (thousands)  
0  1990                  152563212.0  Both Sexes                   5309667.699  
1  1990                   82378628.0  Both Sexes                   1144463.062  
2  1990                   70184584.0  Both Sexes                   4165204.637  
3  1990                   11075966.0  Both Sexes                    510057.629  
4  1990                   59105261.0  Both Sexes                   3655147.008

In [13]:
# Add values in table 3 into the joined table, which can be derived by:
#    100*International migrant stock/(Population*1000)
joined_table["Migrant Percentage of Population"] = 100*joined_table["International Migrant Stock"]/(joined_table["Total Population (thousands)"]*1000)
joined_table.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

   Year  International Migrant Stock      Gender  \
0  1990                  152563212.0  Both Sexes   
1  1990                   82378628.0  Both Sexes   
2  1990                   70184584.0  Both Sexes   
3  1990                   11075966.0  Both Sexes   
4  1990                   59105261.0  Both Sexes   

   Total Population (thousands)  Migrant Percentage of Population  
0                   5309667.699                          2.873310  
1                   1144463.062                          7.198015  
2                   4165204.637                          1.685021  
3                    510057.629                          2.171513  
4                   3655147.008                          1.617042

Moreover, major areas and regions have country code greater or equal to 900, and each individual country has code less than 900. 

**According to principle 4: to make sure we have singular data type in one column/table, we need to split them into two tables.**

Before splitting, we can add one more column to store the region of each country.

In [14]:
# add a new column region for each country to the table
def region_col(table):
    region = []
    major_areas = []     # to store all unique major_areas
    for i in range(len(table)):
        if table.iloc[i,]["Country Code"] >= 900:
            major_areas.append(table.iloc[i,]["Destination"])  # store the major area 
        region.append(major_areas[-1])  # current country's region is the last value in the region list 
    table["Region"] = region 
    return table

joined_table = region_col(joined_table) 
joined_table.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

   Year  International Migrant Stock      Gender  \
0  1990                  152563212.0  Both Sexes   
1  1990                   82378628.0  Both Sexes   
2  1990                   70184584.0  Both Sexes   
3  1990                   11075966.0  Both Sexes   
4  1990                   59105261.0  Both Sexes   

   Total Population (thousands)  Migrant Percentage of Population  \
0                   5309667.699                          2.873310   
1                   1144463.062                          7.198015   
2                   4165204.637                          1.685021   
3                    510057.629                          2.171513   
4                   3655147.008                          1.617042   

                                              Region  
0                                              WORLD  
1                                  Developed regions  
2                                 Developing regions  
3                          Least developed countries  
4  Less developed regions excluding least develop...

In [15]:
# reorder columns
joined_table = joined_table[["Order","Destination","Region","Country Code","Year","Gender",
                             "International Migrant Stock","Total Population (thousands)","Migrant Percentage of Population"]]
joined_table.head()

Order                                        Destination  \
0      1                                              WORLD   
1      2                                  Developed regions   
2      3                                 Developing regions   
3      4                          Least developed countries   
4      5  Less developed regions excluding least develop...   

                                              Region  Country Code  Year  \
0                                              WORLD           900  1990   
1                                  Developed regions           901  1990   
2                                 Developing regions           902  1990   
3                          Least developed countries           941  1990   
4  Less developed regions excluding least develop...           934  1990   

       Gender  International Migrant Stock  Total Population (thousands)  \
0  Both Sexes                  152563212.0                   5309667.699   
1  Both Sexes                   82378628.0                   1144463.062   
2  Both Sexes                   70184584.0                   4165204.637   
3  Both Sexes                   11075966.0                    510057.629   
4  Both Sexes                   59105261.0                   3655147.008   

   Migrant Percentage of Population  
0                          2.873310  
1                          7.198015  
2                          1.685021  
3                          2.171513  
4                          1.617042

In [16]:
# Split the joined table to "major_area" and "countries"
major_area = joined_table[(joined_table['Country Code'] >= 900)]
countries = joined_table[(joined_table['Country Code'] < 900)] 

In [17]:
major_area.head()

Order                                        Destination  \
0      1                                              WORLD   
1      2                                  Developed regions   
2      3                                 Developing regions   
3      4                          Least developed countries   
4      5  Less developed regions excluding least develop...   

                                              Region  Country Code  Year  \
0                                              WORLD           900  1990   
1                                  Developed regions           901  1990   
2                                 Developing regions           902  1990   
3                          Least developed countries           941  1990   
4  Less developed regions excluding least develop...           934  1990   

       Gender  International Migrant Stock  Total Population (thousands)  \
0  Both Sexes                  152563212.0                   5309667.699   
1  Both Sexes                   82378628.0                   1144463.062   
2  Both Sexes                   70184584.0                   4165204.637   
3  Both Sexes                   11075966.0                    510057.629   
4  Both Sexes                   59105261.0                   3655147.008   

   Migrant Percentage of Population  
0                          2.873310  
1                          7.198015  
2                          1.685021  
3                          2.171513  
4                          1.617042

We find the distination column is exactly the same as region column, thus we can drop the region column here.

In [18]:
# Reset index and drop column 'data type'
tidy_major_area = (major_area.
              reset_index().
              drop(columns=['Region',"index"],axis = 1))
tidy_major_area.sort_values(["Order","Year"])

Order Destination  Country Code  Year      Gender  \
0        1       WORLD           900  1990  Both Sexes   
198      1       WORLD           900  1990        Male   
396      1       WORLD           900  1990      Female   
33       1       WORLD           900  1995  Both Sexes   
231      1       WORLD           900  1995        Male   
..     ...         ...           ...   ...         ...   
362    256   Polynesia           957  2010        Male   
560    256   Polynesia           957  2010      Female   
197    256   Polynesia           957  2015  Both Sexes   
395    256   Polynesia           957  2015        Male   
593    256   Polynesia           957  2015      Female   

     International Migrant Stock  Total Population (thousands)  \
0                    152563212.0                   5309667.699   
198                   77747510.0                   2670423.701   
396                   74815702.0                   2639243.998   
33                   160801752.0                   5735123.084   
231                   81737477.0                   2886635.893   
..                           ...                           ...   
362                      39338.0                       336.596   
560                      33674.0                       323.513   
197                      72120.0                       684.460   
395                      38759.0                       348.345   
593                      33361.0                       336.115   

     Migrant Percentage of Population  
0                            2.873310  
198                          2.911430  
396                          2.834740  
33                           2.803806  
231                          2.831583  
..                                ...  
362                         11.687008  
560                         10.408855  
197                         10.536774  
395                         11.126613  
593                          9.925472  

[594 rows x 8 columns]

In [19]:
tidy_major_area.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

   Year      Gender  International Migrant Stock  \
0  1990  Both Sexes                  152563212.0   
1  1990  Both Sexes                   82378628.0   
2  1990  Both Sexes                   70184584.0   
3  1990  Both Sexes                   11075966.0   
4  1990  Both Sexes                   59105261.0   

   Total Population (thousands)  Migrant Percentage of Population  
0                   5309667.699                          2.873310  
1                   1144463.062                          7.198015  
2                   4165204.637                          1.685021  
3                    510057.629                          2.171513  
4                   3655147.008                          1.617042

In [20]:
# Reset index
tidy_countries = (countries.  
              reset_index().
              drop(columns=['index'],axis = 1))
tidy_countries.sort_values(["Order","Year"]) 

Order                Destination          Region  Country Code  Year  \
0         9                    Burundi  Eastern Africa           108  1990   
1392      9                    Burundi  Eastern Africa           108  1990   
2784      9                    Burundi  Eastern Africa           108  1990   
232       9                    Burundi  Eastern Africa           108  1995   
1624      9                    Burundi  Eastern Africa           108  1995   
...     ...                        ...             ...           ...   ...   
2551    265  Wallis and Futuna Islands       Polynesia           876  2010   
3943    265  Wallis and Futuna Islands       Polynesia           876  2010   
1391    265  Wallis and Futuna Islands       Polynesia           876  2015   
2783    265  Wallis and Futuna Islands       Polynesia           876  2015   
4175    265  Wallis and Futuna Islands       Polynesia           876  2015   

          Gender  International Migrant Stock  Total Population (thousands)  \
0     Both Sexes                     333110.0                      5613.141   
1392        Male                     163267.0                      2755.028   
2784      Female                     169843.0                      2858.113   
232   Both Sexes                     254853.0                      6239.030   
1624        Male                     124165.0                      3054.367   
...          ...                          ...                           ...   
2551        Male                       1401.0                           NaN   
3943      Female                       1375.0                           NaN   
1391  Both Sexes                       2849.0                        13.151   
2783        Male                       1438.0                           NaN   
4175      Female                       1411.0                           NaN   

      Migrant Percentage of Population  
0                             5.934467  
1392                          5.926147  
2784                          5.942487  
232                           4.084818  
1624                          4.065163  
...                                ...  
2551                               NaN  
3943                               NaN  
1391                         21.663752  
2783                               NaN  
4175                               NaN  

[4176 rows x 9 columns]

# Table 4: Female migrants as a percentage of the international migrant stock

In [21]:
table4 = dfs['Table 4'] 
# Prepare for cleaning by giving proper variable names for the table and dropping not useful columns
table4 = (table4.
          rename(columns = {'Unnamed: 0':"Order",
                            'Unnamed: 1':"Destination",
                            'Unnamed: 2':'Notes',
                            'Unnamed: 3':'Country Code',
                            'Unnamed: 4':'Data Type',
                            1990:"1990.2", 1995:"1995.2", 2000:'2000.2',
                            2005:'2005.2', 2010:'2010.2', 2015:'2015.2'}).
          drop(columns=['Notes','Data Type'],axis = 1))

# Conduct data cleaning for table 4
table4 = tidy_table(table4,"Female Migrants Percentage") 
table4 = table4.drop(columns = ["Gender"])
table4

Order                                        Destination  Country Code  \
0         1                                              WORLD           900   
1         2                                  Developed regions           901   
2         3                                 Developing regions           902   
3         4                          Least developed countries           941   
4         5  Less developed regions excluding least develop...           934   
...     ...                                                ...           ...   
1585    261                                              Samoa           882   
1586    262                                            Tokelau           772   
1587    263                                              Tonga           776   
1588    264                                             Tuvalu           798   
1589    265                          Wallis and Futuna Islands           876   

      Year Female Migrants Percentage  
0     1990                   49.03915  
1     1990                  51.123977  
2     1990                  46.592099  
3     1990                  47.261155  
4     1990                  46.466684  
...    ...                        ...  
1585  2015                  49.908704  
1586  2015                  52.156057  
1587  2015                  45.437096  
1588  2015                  44.680851  
1589  2015                   49.52615  

[1590 rows x 5 columns]

# Table 5: Annual Rate of Change of the Migrant Stock by Sex

In [22]:
table5 = dfs['Table 5'] 
# Prepare for cleaning by giving proper variable names for the table and dropping not useful columns
table5 = (table5.
          rename(columns = {'Unnamed: 0':"Order",
                            'Unnamed: 1':"Destination",
                            'Unnamed: 2':'Notes',
                            'Unnamed: 3':'Country Code',
                            'Unnamed: 4':'Data Type',
                            '1990-1995':"1990-1995.0", '1995-2000':"1995-2000.0", '2000-2005':'2000-2005.0',
                            '2005-2010':'2005-2010.0', '2010-2015':'2010-2015.0'}).
          drop(columns=['Notes','Data Type'],axis = 1))

# Conduct data cleaning for table 5
table5 = tidy_table(table5,"Annual Rate of Change of The Migrant Stock")  
table5

Order                                        Destination  Country Code  \
0         1                                              WORLD           900   
1         2                                  Developed regions           901   
2         3                                 Developing regions           902   
3         4                          Least developed countries           941   
4         5  Less developed regions excluding least develop...           934   
...     ...                                                ...           ...   
3970    261                                              Samoa           882   
3971    262                                            Tokelau           772   
3972    263                                              Tonga           776   
3973    264                                             Tuvalu           798   
3974    265                          Wallis and Futuna Islands           876   

           Year Annual Rate of Change of The Migrant Stock      Gender  
0     1990-1995                                   1.051865  Both Sexes  
1     1990-1995                                   2.275847  Both Sexes  
2     1990-1995                                  -0.487389  Both Sexes  
3     1990-1995                                   1.118175  Both Sexes  
4     1990-1995                                  -0.803244  Both Sexes  
...         ...                                        ...         ...  
3970  2010-2015                                  -0.545343      Female  
3971  2010-2015                                    2.60325      Female  
3972  2010-2015                                   2.526318      Female  
3973  2010-2015                                  -1.819436      Female  
3974  2010-2015                                   0.516899      Female  

[3975 rows x 6 columns]

Since each country/region's annual rate of change has three categories 'Both sexes', 'Male' and 'Female'. For clarity, we can also convert the gender column into three individual columns by principle 3.

In [23]:
table5 = (table5.
          replace('..', -1).   # prepare for using pivot table which cannot contain NaN
          pivot_table(index = ["Order","Destination","Country Code","Year"],  # principle 3
                      columns = "Gender",
                      values = "Annual Rate of Change of The Migrant Stock").
                reset_index().
                rename_axis(None, axis=1).
          replace(-1, np.nan)) # change missing values back to NaN
table5

Order                Destination  Country Code       Year  Both Sexes  \
0         1                      WORLD           900  1990-1995    1.051865   
1         1                      WORLD           900  1995-2000    1.428058   
2         1                      WORLD           900  2000-2005    2.042124   
3         1                      WORLD           900  2005-2010    2.954160   
4         1                      WORLD           900  2010-2015    1.890991   
...     ...                        ...           ...        ...         ...   
1320    265  Wallis and Futuna Islands           876  1990-1995    3.617880   
1321    265  Wallis and Futuna Islands           876  1995-2000    3.636508   
1322    265  Wallis and Futuna Islands           876  2000-2005    3.203177   
1323    265  Wallis and Futuna Islands           876  2005-2010    3.204660   
1324    265  Wallis and Futuna Islands           876  2010-2015    0.519140   

        Female      Male  
0     1.104667  1.000922  
1     1.405044  1.450294  
2     1.928080  2.151575  
3     2.737012  3.159228  
4     1.867837  1.912603  
...        ...       ...  
1320  3.886601  3.364378  
1321  3.884553  3.396526  
1322  3.217252  3.189382  
1323  3.211913  3.197545  
1324  0.516899  0.521340  

[1325 rows x 7 columns]

# Table 6: Estimated Refugee Stock at Mid-Year

In [24]:
table6 = dfs['Table 6'] 
# Rename columns, drop not useful columns
# replace '..' values with NaN 
table6 = (table6.
          rename(columns = {'Unnamed: 0':"Order",
                            'Unnamed: 1':"Destination",
                            'Unnamed: 2':'Notes',
                            'Unnamed: 3':'Country Code',
                            'Unnamed: 4':"Data Type",
                            1990:"1990.0", 1995:"1995.0", 2000:'2000.0',
                            2005:'2005.0', 2010:'2010.0', 2015:'2015.0'}).
          drop(columns=['Notes', 'Data Type'],axis = 1).
          replace("..",np.nan))
table6.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

       1990.0      1995.0      2000.0      2005.0    2010.0    2015.0  \
0  18836571.0  17853840.0  15827803.0  13276733.0  15370755  19577474   
1   2014564.0   3609670.0   2997256.0   2361229.0   2046917   1954224   
2  16822007.0  14244170.0  12830547.0  10915504.0  13323838  17623250   
3   5048391.0   5160131.0   3047488.0   2363782.0   1957884   3443582   
4  11773616.0   9084039.0   9783059.0   8551722.0  11365954  14179668   

      1990.1     1995.1     2000.1     2005.1     2010.1     2015.1  \
0  12.346732  11.103013   9.164736   6.941389   6.932687   8.033424   
1   2.445494   3.910511   2.899391   2.015025   1.544140   1.391085   
2  23.968236  20.795958  18.507035  14.733162  14.944759  17.073768   
3  45.565880  44.041961  30.221557  24.082430  19.533425  28.801534   
4  19.919743  15.999082  16.513130  13.305391  14.363526  15.537313   

   1990-1995  1995-2000  2000-2005  2005-2010  2010-2015  
0  -2.123497  -3.837069  -5.557223  -0.025089   2.947267  
1   9.388424  -5.983348  -7.277379  -5.323293  -2.087656  
2  -2.839417  -2.332154  -4.561000   0.285195   2.663652  
3  -0.680327  -7.531747  -4.541459  -4.187109   7.766031  
4  -4.383600   0.632489  -4.319731   1.530456   1.571047

Table 6 is slightly different from the previous tables, which contains multiple type of data. 

Column '1990.0' to '2015.0' represents Estimated refugee stock at mid-year (both sexes).

Column '1990.1' to '2015.1' represents Refugees as a percentage of the international migrant stock.

Column '1990-1995' to '2010-2015' represents Annual rate of change of the refugee stock.

**Thus, by principle 4, we need to split it into several tables** and cannot directly use the tidy function defined before. 

In [25]:
# set index and split tables
table6 = table6.set_index(["Order","Destination","Country Code"])
refugee_stock = table6[['1990.0', '1995.0', '2000.0', '2005.0', '2010.0', '2015.0']].copy()
Refugees_percentage = table6[['1990.1', '1995.1', '2000.1', '2005.1', '2010.1', '2015.1']].copy()
rate_of_change = table6[['1990-1995', '1995-2000', '2000-2005', '2005-2010', '2010-2015']].copy()

In [26]:
refugee_stock = (refugee_stock.reset_index().
                 melt(id_vars=["Order","Destination","Country Code"],  # principle 1
                      var_name = "Year", value_name = "Refugee Stock").
                 assign(Year = lambda x: x.Year.str[:-2].astype(str)))
refugee_stock

Order                                        Destination  Country Code  \
0         1                                              WORLD           900   
1         2                                  Developed regions           901   
2         3                                 Developing regions           902   
3         4                          Least developed countries           941   
4         5  Less developed regions excluding least develop...           934   
...     ...                                                ...           ...   
1585    261                                              Samoa           882   
1586    262                                            Tokelau           772   
1587    263                                              Tonga           776   
1588    264                                             Tuvalu           798   
1589    265                          Wallis and Futuna Islands           876   

      Year  Refugee Stock  
0     1990     18836571.0  
1     1990      2014564.0  
2     1990     16822007.0  
3     1990      5048391.0  
4     1990     11773616.0  
...    ...            ...  
1585  2015            0.0  
1586  2015            0.0  
1587  2015            0.0  
1588  2015            0.0  
1589  2015            0.0  

[1590 rows x 5 columns]

In [27]:
Refugees_percentage = (Refugees_percentage.reset_index().
                       melt(id_vars=["Order","Destination","Country Code"],  # principle 1
                       var_name = "Year", value_name = "Refugee Percentage").
                       assign(Year = lambda x: x.Year.str[:-2].astype(str)))
Refugees_percentage

Order                                        Destination  Country Code  \
0         1                                              WORLD           900   
1         2                                  Developed regions           901   
2         3                                 Developing regions           902   
3         4                          Least developed countries           941   
4         5  Less developed regions excluding least develop...           934   
...     ...                                                ...           ...   
1585    261                                              Samoa           882   
1586    262                                            Tokelau           772   
1587    263                                              Tonga           776   
1588    264                                             Tuvalu           798   
1589    265                          Wallis and Futuna Islands           876   

      Year  Refugee Percentage  
0     1990           12.346732  
1     1990            2.445494  
2     1990           23.968236  
3     1990           45.565880  
4     1990           19.919743  
...    ...                 ...  
1585  2015            0.000000  
1586  2015            0.000000  
1587  2015            0.000000  
1588  2015            0.000000  
1589  2015            0.000000  

[1590 rows x 5 columns]

In [28]:
rate_of_change = (rate_of_change.reset_index().
                       melt(id_vars=["Order","Destination","Country Code"],  # principle 1
                       var_name = "Year", value_name = "Rate of Change"))
rate_of_change

Order                                        Destination  Country Code  \
0         1                                              WORLD           900   
1         2                                  Developed regions           901   
2         3                                 Developing regions           902   
3         4                          Least developed countries           941   
4         5  Less developed regions excluding least develop...           934   
...     ...                                                ...           ...   
1320    261                                              Samoa           882   
1321    262                                            Tokelau           772   
1322    263                                              Tonga           776   
1323    264                                             Tuvalu           798   
1324    265                          Wallis and Futuna Islands           876   

           Year  Rate of Change  
0     1990-1995       -2.123497  
1     1990-1995        9.388424  
2     1990-1995       -2.839417  
3     1990-1995       -0.680327  
4     1990-1995       -4.383600  
...         ...             ...  
1320  2010-2015             NaN  
1321  2010-2015             NaN  
1322  2010-2015             NaN  
1323  2010-2015             NaN  
1324  2010-2015             NaN  

[1325 rows x 5 columns]

We can find that the Refugees_percentage tables shares some values with the table 4 (Female migrants as a percentage of the international migrant stock), therefore we can also join this table with table4.

In [29]:
table4 = table4.merge(Refugees_percentage, on=["Order","Destination","Country Code","Year"])
table4

Order                                        Destination  Country Code  \
0         1                                              WORLD           900   
1         2                                  Developed regions           901   
2         3                                 Developing regions           902   
3         4                          Least developed countries           941   
4         5  Less developed regions excluding least develop...           934   
...     ...                                                ...           ...   
1585    261                                              Samoa           882   
1586    262                                            Tokelau           772   
1587    263                                              Tonga           776   
1588    264                                             Tuvalu           798   
1589    265                          Wallis and Futuna Islands           876   

      Year Female Migrants Percentage  Refugee Percentage  
0     1990                   49.03915           12.346732  
1     1990                  51.123977            2.445494  
2     1990                  46.592099           23.968236  
3     1990                  47.261155           45.565880  
4     1990                  46.466684           19.919743  
...    ...                        ...                 ...  
1585  2015                  49.908704            0.000000  
1586  2015                  52.156057            0.000000  
1587  2015                  45.437096            0.000000  
1588  2015                  44.680851            0.000000  
1589  2015                   49.52615            0.000000  

[1590 rows x 6 columns]

Similarly, the rate_of_change table also shares some commons with table 5 (Annual Rate of Change of the Migrant Stock by Sex). Thus we can join these two tables into one single table.

In [30]:
table5 = table5.merge(rate_of_change, on=["Order","Destination","Country Code","Year"])
table5 = table5.rename(columns = {'Rate of Change':"Refugees"})
table5

Order                Destination  Country Code       Year  Both Sexes  \
0         1                      WORLD           900  1990-1995    1.051865   
1         1                      WORLD           900  1995-2000    1.428058   
2         1                      WORLD           900  2000-2005    2.042124   
3         1                      WORLD           900  2005-2010    2.954160   
4         1                      WORLD           900  2010-2015    1.890991   
...     ...                        ...           ...        ...         ...   
1320    265  Wallis and Futuna Islands           876  1990-1995    3.617880   
1321    265  Wallis and Futuna Islands           876  1995-2000    3.636508   
1322    265  Wallis and Futuna Islands           876  2000-2005    3.203177   
1323    265  Wallis and Futuna Islands           876  2005-2010    3.204660   
1324    265  Wallis and Futuna Islands           876  2010-2015    0.519140   

        Female      Male  Refugees  
0     1.104667  1.000922 -2.123497  
1     1.405044  1.450294 -3.837069  
2     1.928080  2.151575 -5.557223  
3     2.737012  3.159228 -0.025089  
4     1.867837  1.912603  2.947267  
...        ...       ...       ...  
1320  3.886601  3.364378       NaN  
1321  3.884553  3.396526       NaN  
1322  3.217252  3.189382       NaN  
1323  3.211913  3.197545       NaN  
1324  0.516899  0.521340       NaN  

[1325 rows x 8 columns]

In [31]:
table6 = refugee_stock
table6.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

   Year  Refugee Stock  
0  1990     18836571.0  
1  1990      2014564.0  
2  1990     16822007.0  
3  1990      5048391.0  
4  1990     11773616.0

# Summary & Export

We have cleaned the orginal 6 tables into the following tables:

In [32]:
joined_table.sort_values(["Order","Year"])

Order                Destination     Region  Country Code  Year  \
0         1                      WORLD      WORLD           900  1990   
1590      1                      WORLD      WORLD           900  1990   
3180      1                      WORLD      WORLD           900  1990   
265       1                      WORLD      WORLD           900  1995   
1855      1                      WORLD      WORLD           900  1995   
...     ...                        ...        ...           ...   ...   
2914    265  Wallis and Futuna Islands  Polynesia           876  2010   
4504    265  Wallis and Futuna Islands  Polynesia           876  2010   
1589    265  Wallis and Futuna Islands  Polynesia           876  2015   
3179    265  Wallis and Futuna Islands  Polynesia           876  2015   
4769    265  Wallis and Futuna Islands  Polynesia           876  2015   

          Gender  International Migrant Stock  Total Population (thousands)  \
0     Both Sexes                  152563212.0                   5309667.699   
1590        Male                   77747510.0                   2670423.701   
3180      Female                   74815702.0                   2639243.998   
265   Both Sexes                  160801752.0                   5735123.084   
1855        Male                   81737477.0                   2886635.893   
...          ...                          ...                           ...   
2914        Male                       1401.0                           NaN   
4504      Female                       1375.0                           NaN   
1589  Both Sexes                       2849.0                        13.151   
3179        Male                       1438.0                           NaN   
4769      Female                       1411.0                           NaN   

      Migrant Percentage of Population  
0                             2.873310  
1590                          2.911430  
3180                          2.834740  
265                           2.803806  
1855                          2.831583  
...                                ...  
2914                               NaN  
4504                               NaN  
1589                         21.663752  
3179                               NaN  
4769                               NaN  

[4770 rows x 9 columns]

In [34]:
table4.sort_values(["Order","Year"])

Order                Destination  Country Code  Year  \
0         1                      WORLD           900  1990   
265       1                      WORLD           900  1995   
530       1                      WORLD           900  2000   
795       1                      WORLD           900  2005   
1060      1                      WORLD           900  2010   
...     ...                        ...           ...   ...   
529     265  Wallis and Futuna Islands           876  1995   
794     265  Wallis and Futuna Islands           876  2000   
1059    265  Wallis and Futuna Islands           876  2005   
1324    265  Wallis and Futuna Islands           876  2010   
1589    265  Wallis and Futuna Islands           876  2015   

     Female Migrants Percentage  Refugee Percentage  
0                      49.03915           12.346732  
265                    49.16879           11.103013  
530                   49.112244            9.164736  
795                   48.832993            6.941389  
1060                   48.30566            6.932687  
...                         ...                 ...  
529                   48.869048            0.000000  
794                   49.478908            0.000000  
1059                  49.513742            0.000000  
1324                    49.5317            0.000000  
1589                   49.52615            0.000000  

[1590 rows x 6 columns]

In [35]:
table5.sort_values(["Order","Year"])

Order                Destination  Country Code       Year  Both Sexes  \
0         1                      WORLD           900  1990-1995    1.051865   
1         1                      WORLD           900  1995-2000    1.428058   
2         1                      WORLD           900  2000-2005    2.042124   
3         1                      WORLD           900  2005-2010    2.954160   
4         1                      WORLD           900  2010-2015    1.890991   
...     ...                        ...           ...        ...         ...   
1320    265  Wallis and Futuna Islands           876  1990-1995    3.617880   
1321    265  Wallis and Futuna Islands           876  1995-2000    3.636508   
1322    265  Wallis and Futuna Islands           876  2000-2005    3.203177   
1323    265  Wallis and Futuna Islands           876  2005-2010    3.204660   
1324    265  Wallis and Futuna Islands           876  2010-2015    0.519140   

        Female      Male  Refugees  
0     1.104667  1.000922 -2.123497  
1     1.405044  1.450294 -3.837069  
2     1.928080  2.151575 -5.557223  
3     2.737012  3.159228 -0.025089  
4     1.867837  1.912603  2.947267  
...        ...       ...       ...  
1320  3.886601  3.364378       NaN  
1321  3.884553  3.396526       NaN  
1322  3.217252  3.189382       NaN  
1323  3.211913  3.197545       NaN  
1324  0.516899  0.521340       NaN  

[1325 rows x 8 columns]

In [36]:
table6.head()

Order                                        Destination  Country Code  \
0      1                                              WORLD           900   
1      2                                  Developed regions           901   
2      3                                 Developing regions           902   
3      4                          Least developed countries           941   
4      5  Less developed regions excluding least develop...           934   

   Year  Refugee Stock  
0  1990     18836571.0  
1  1990      2014564.0  
2  1990     16822007.0  
3  1990      5048391.0  
4  1990     11773616.0

In [ ]:
with pd.ExcelWriter('~/Desktop/tidy_tables.xlsx') as writer:  
    joined_table.to_excel(writer, sheet_name='Migrant Stock and Population')
    table4.to_excel(writer, sheet_name='Female and Refugee Percentage')
    table5.to_excel(writer, sheet_name='Annual Rate of Change')
    table6.to_excel(writer, sheet_name='Estimate Refugee Stock')
writer.save()